---

# Cloning duplicati

- name: Creating duplicati directory for duplicati source code
  file:
    path: "/home/{{ gogs_user }}/duplicati"
    state: directory
    mode: 0755
    owner: "{{ gogs_user }}"
    group: "{{ gogs_user }}"

- name: Check if duplicati has been cloned successfully already
  stat: 
    path: "/home/{{ gogs_user }}/duplicati/ansible_git_clone_complete"
  register: duplicati_clone

- name: Cloning duplicati
  git:
    repo: http://bcs:33333/bauli/duplicati.git
    dest: "/home/{{ gogs_user }}/duplicati"
    refspec: '+refs/pull/*:refs/heads/*'
  become_user: "{{ gogs_user }}"
  become: yes
  when: not duplicati_clone.stat.exists

- name: Adding a file to denote duplicati has been completely cloned
  file: 
    path: "/home/{{ gogs_user }}/duplicati/ansible_git_clone_complete"
    state: touch
    owner: "{{ gogs_user }}"
    group: "{{ gogs_user }}"

# Configuring compilation and run environment for duplicati

- name: Ensure gnupg is installed.
  package: name=gnupg state=present

- name: Ensure ca-certificates is installed.
  package: name=ca-certificates state=present

- name: Ensure debhelper is installed for compiling dublicati debian packages
  package: name=debhelper state=present

- name: "Checking if /etc/apt/sources.list.d/mono-official-stable.list is present"
  stat:
    path: "/etc/apt/sources.list.d/mono-official-stable.list"
  register: mono_list

- name: Adding mono repository to the system
  shell: |
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  args:
    executable: /bin/bash
  become: yes
  when: not mono_list.stat.exists
  register: mono

  #- name: Test
  #  shell: |
  #    cat /etc/apt/sources.list.d/mono-official-stable.list
  #  args:
  #    executable: /bin/bash
  #  become: yes
  #  register: cat_apt_list
  #
  #- debug:
  #    var: cat_apt_list.stdout_lines
  #

- name: apt update 
  shell: |
    sudo apt update
  args:
    executable: /bin/bash
  become: yes
  when: mono.changed

- name: Ensure mono-devel is installed, this will take a lot of time... A LOT !!! - it does heavy compiling....
  package: name=mono-devel state=present
  tags: mono1

- name: Ensure nuget is installed, required by duplicati build and install scripts to download .NET libraries
  package: name=nuget state=present
  tags: mono1

- name: Getting nuget version
  shell: |
    nuget help | head -1
  register: nuget_version

- debug:
    var: nuget_version

- name: update nuget
  shell: |
    nuget update -self
  args:
    executable: /bin/bash
  become: yes
  register: nuget_update
  when: '"NuGet Version: 5.0.2.5988" not in nuget_version.stdout'
  tags: mono1

- debug:
    var: nuget_update.stdout_lines
  tags: mono1
  when: nuget_update.changed

- name: Ensure gtk_sharp2 is installed for dublicati UI
  package: name=gtk-sharp2 state=present
  tags: mono2

- name: Ensure mono-complete is installed for most of the package - if needed I do not know....
  package: name=mono-complete state=present
  tags: mono3

- name: Ensure mono-xsp4 is installed for .NET ASP support - if needed I do not know...
  package: name=mono-xsp4 state=present
  tags: mono4

- name: Check if debian packages have been build 
  stat: 
    path: "/home/{{ gogs_user }}/duplicati/ansible_debian_packages_build"
  register: duplicati_debian

- debug:
    var: duplicati_debian

- name: Building duplicati debian packages
  shell: |
    cd /home/{{ gogs_user }}/duplicati/Installer/debian 
    export MONO_GC_PARAMS=major=marksweep-conc; ENV=../.. bash build-package.sh
  args:
    executable: /bin/bash
  become: yes
  when: not duplicati_debian.stat.exists
  tags: dublicati_build

- name: Adding a file to denote duplicati has been completely cloned
  file: 
    path: "/home/{{ gogs_user }}/duplicati/ansible_debian_packages_build"
    state: touch


