---

# Add specified repository into sources list.
- apt_repository:
    repo: deb ppa:gophers/archive
    state: present
  become: yes 

- apt_repository:
    repo: deb ppa:longsleep/golang-backports
    state: present
  become: yes 

- name: Updating repositories cache and installing golang 
  apt:
    name: golang-go
    update_cache: yes
  become: yes 

