# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.box = "geerlingguy/ubuntu1404"
  config.vm.box = "geerlingguy/ubuntu1804"
  config.vm.box_version = "1.0.0"
  if Vagrant.has_plugin?("vagrant-cachier")
  # Share cache among instances of the same base box.
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      owner: "_apt",
      group: "_apt"
    }
  end

  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "bcc"
#    v.memory = 512
#    v.memory = 1024
#    v.memory = 2048
    v.memory = 2560
#    v.memory = 1536
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "bcc"
  config.vm.network :private_network, ip: "192.168.33.23"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :bcc do |bcc|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.become = true
#    ansible.tags = "duplicati"
#    ansible.tags = "mkswap"
#    ansible.tags = "vimdev"
#    ansible.skip_tags = ["mono1","mono2","mono3","mono4","duplicati_build","gogs_build"]
  end

end
